### ISSUE TITLE
When getting multiple hits, iterate over all possible plaintexts

### ISSUE THREAD

**Issue by Iaotle** [djosix/padding_oracle.py#3]
Sometimes the oracle might return two results that are valid. This script will simply ignore those blocks.
I added the following lines to make the script work in my specific case:
![image](https://user-images.githubusercontent.com/43072246/196776203-d1b33e23-2851-4c08-b0f9-6ec80d22dfe0.png)
![image](https://user-images.githubusercontent.com/43072246/196779943-b9a85f38-1f47-4e2d-b1d5-8f528740a7c9.png)
I think it makes sense to iterate over the possible plaintexts if the number of hits is low (2 in this case). I also noticed that the hits array isn't sorted, which would also have solved it in this case:
![image](https://user-images.githubusercontent.com/43072246/196779998-278ca023-7a87-4a0d-8630-13b9de9c46e4.png)

**Comment by djosix** [comment]
Thanks for pointing out this mistake!
I have fixed this problem and added some test scripts.
